apiVersion: v1
kind: Service
metadata:
  name: spring-kubernetes-service
  labels:
    app: spring-boot-deployment
spec:
  selector:
    app: spring-boot-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
---
apiVersion: apps/v1
metadata:
  name: spring-kubernetes-deployment-deploy
kind: Deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-deployment
  template:
    metadata:
      labels:
        app: spring-boot-deployment
    spec:
      containers:
        - name: spring-kubernetes-deployment
          image: fyuizee/spring-kubernetes-deployment
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s